// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSPy-A12i6bLLHsIe6DPRdEJn-_eyPKek',
    appId: '1:757795730958:web:54a687f64954ffc9db2e5f',
    messagingSenderId: '757795730958',
    projectId: 'vyomanew-47887',
    authDomain: 'vyomanew-47887.firebaseapp.com',
    storageBucket: 'vyomanew-47887.firebasestorage.app',
    measurementId: 'G-YZ06HKYE67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKp1uMYzJfdRwn3LowNqNd-NDvwLmmfeM',
    appId: '1:757795730958:android:b2ee510b074cc03edb2e5f',
    messagingSenderId: '757795730958',
    projectId: 'vyomanew-47887',
    storageBucket: 'vyomanew-47887.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd6jhY0OWWmmhtD7ricvZ5MpSnvVz_K70',
    appId: '1:757795730958:ios:4911923b3fbdc31adb2e5f',
    messagingSenderId: '757795730958',
    projectId: 'vyomanew-47887',
    storageBucket: 'vyomanew-47887.firebasestorage.app',
    iosBundleId: 'com.example.deliveryAgentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd6jhY0OWWmmhtD7ricvZ5MpSnvVz_K70',
    appId: '1:757795730958:ios:4911923b3fbdc31adb2e5f',
    messagingSenderId: '757795730958',
    projectId: 'vyomanew-47887',
    storageBucket: 'vyomanew-47887.firebasestorage.app',
    iosBundleId: 'com.example.deliveryAgentApp',
  );
}
